# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/online-spreadsheet-skiller',
                'doc_host': 'https://aiola-lab.github.io',
                'git_url': 'https://github.com/aiola-lab/online-spreadsheet-skiller',
                'lib_path': 'online_spreadsheet_skiller'},
  'syms': { 'online_spreadsheet_skiller.core': { 'online_spreadsheet_skiller.core.foo': ( 'core.html#foo',
                                                                                          'online_spreadsheet_skiller/core.py')}}}